### ISSUE TITLE
Não lê formato ex fat,  vai ter uma versão que le ex fat? Preciso muito disso 

### ISSUE THREAD

**Issue by Aleatorio0** [israpps/wLaunchELF_ISR#16]

**Comment by israpps** [comment]
I can't add exfat support to this fork.

Please refer to [latest wLaunchELF](https://github.com/ps2homebrew/wLaunchELF)

The only version with exfat support around

**Comment by INDRAPhilip** [comment]
@israpps The latest versions of wLaunchELF with exfat have many bugs, that must be why it won't bring it to this fork, but ask me a question on this fork is there support for MX4SIO or Ilink adoriá testa to know now that I have purchased one.

**Comment by israpps** [comment]
> @israpps The latest versions of wLaunchELF with exfat have many bugs, that must be why it won't bring it to this fork, but ask me a question on this fork is there support for MX4SIO or Ilink adoriá testa to know now that I have purchased one.

You bought an MX4SIO or a iLink driver? or both?

TBH, i don't think it's possible to implement them on my fork, since they depend on BDM and many backend changes of latest SDK

**Comment by INDRAPhilip** [comment]
> You bought an MX4SIO or a iLink driver? or both?

I understand that I bought an MX4SIO, but I am also considering buying an adapter with Ilink support

>TBH, i don't think it's possible to implement them on my fork, since they depend on BDM and many backend changes of latest SDK

The new versions are very unstable from wLaunchELF that's why I usually use your fork, too bad we won't see MX4SIO or Ilink, but still thanks for the reply.

**Comment by israpps** [comment]
Against all odds, copy pasting the newer IRX drivers and using them allowed the usage of exfat devices.

detection worked well, and to test if it was reliable, i copied ~200 files from fat32 device to exfat device and it worked well.
