### ISSUE TITLE
MX4SIO driver locks access to `mc1:/`

### ISSUE THREAD

**Issue by MayanKoyote** [israpps/wLaunchELF_ISR#36]
I don't know how it worked (if it worked) in the past and how it should work at all (maybe this is normal behavior), but nevertheless:
Bilds 6700656 and 2d9b64e were used (both 'BOOT-EXFAT-NO_NETWORK-MX4SIO'), behavior is the same.

1. If a memory card with FMCB (and wLaunchELF) is inserted into slot 2, it is not possible to look at the files on this card, i.e. at 'mc1:'. Neither directories nor files are displayed, the root is empty. If the same card is in slot 1 - then its content is visible.
2. If to try in this case (card in slot 2, nothing else) to save the settings, the notice "Failed To Save LAUNCHERELF.CNF" appears. If to add another card into slot 1 and try again to save the settings, the notice "Saved Config (mc0:/SYS-CONF/LAUNCHERELF.CNF)" appears. I.e. when running wLauncheELF from slot 2, it tries to save its config to slot 1.

I compared all this with wLaunchELF 4.42e (which happened to be on one of my old FMCB cards) - with it no such strange behavior was detected.

**Comment by israpps** [comment]
excellent

so the issue is related to the MX4SIO Driver

**Comment by israpps** [comment]
since this issue seems to be cause by the hackish behaviour of the `MX4SIO_BD` driver. I can't guarantee that a solution will be provided...

**Comment by Srandista** [comment]
It's not affecting just MC in 2nd slot, I wasn't able to run FMCB installer from USB drive. I had to run non-MX4SIO build of wLaunchELF, from which the installer run without any issues.

**Comment by israpps** [comment]
> It's not affecting just MC in 2nd slot, I wasn't able to run FMCB installer from USB drive. I had to run non-MX4SIO build of wLaunchELF, from which the installer run without any issues.

Maybe the MX4SIO driver is messing up some sio2 registers

Or for some reason FreeMcBoot installer could not replace the SECRMAN driver

Or maybe your USB is EXFAT and FreeMcBoot installer couldn't detect it.

Lots of possibilities

**Comment by Windows10User2** [comment]
I still have this issue.

**Comment by israpps** [comment]
> I still have this issue.

This is **NOT** an issue. It is a design side effect of how MX4SIO driver works...
