### ISSUE TITLE
no es un problema es una mejora

### ISSUE THREAD

**Issue by steve007iii** [israpps/wLaunchELF_ISR#4]
Para que se abran los archivos con extensión *.VCD
con el emulador de play1 apuntando a 
hdd0:/__common/POPS/POPSTARTER.ELF

Vi una versión que hace esto en esta pagina 👍 https://www.elotrolado.net/hilo_ho-pops-emulador-de-psx-para-ps2_1874054
peor con el gran trabajo que han logrado hasta hora seria un plus adicional +++ muy de apreciar!!! 

![Image text](https://i.imgur.com/NifR4S3.png)

**Comment by israpps** [comment]
El uLaunchELF KHN ya es capaz de hacerlo

**Comment by israpps** [comment]
Primeramente agregar una función de este estilo no tiene sentido si ya el uLaunchELF khn es capaz de hacerlo...
Y segundo no tengo forma de saber qué argumentos pasa el uLaunchELF khn al POPStarter....

Ya que él uLaunchELF khn no lanza juegos de ps1 si la ruta del popstarter está ocupada por otro programa que no sea popstarter (krHACKen lo hizo para que nadie pusiera uLaunchELF en la ruta del popstarter con el fin de aprender que comandos son pasados al POPStarter)

**Comment by israpps** [comment]
https://github.com/israpps/FreeMcBoot-Installer/raw/master/MASS/APPS/wLaunchELF%20KHN/wLaunchELF%20KHN.ELF
