### ISSUE TITLE
[FR] POPStarter VCD support

### ISSUE THREAD

**Issue by 10522** [israpps/wLaunchELF_ISR#50]
You made a great fork, but the only reason I don't use it is that I can't run VCD files. Is it possible to add running VCD files to your fork, as implemented in [uLE_kHn](https://bitbucket.org/ShaolinAssassin/popstarter-documentation-stuff/wiki/uLE_kHn)?

**Comment by israpps** [comment]
> You made a great fork, but the only reason I don't use it is that I can't run VCD files. Is it possible to add running VCD files to your fork, as implemented in [uLE_kHn](https://bitbucket.org/ShaolinAssassin/popstarter-documentation-stuff/wiki/uLE_kHn)?

wLaunchELF KHN is closed source... it would require some reverse engineering, but can be done

**Comment by WolfRamiO74** [comment]
i was about to open a new thread about this!!! can be implemented? is a "must have feature", thanks!!!!

**Comment by israpps** [comment]
It can be done but requires some annoying changes to the ELF loader. Do you really want this on wLaunchELF?

You could try my POPS VCD manager (on PSX-place)

**Comment by WolfRamiO74** [comment]
> It can be done but requires some annoying changes to the ELF loader. Do you really want this on wLaunchELF?
> 
> You could try my POPS VCD manager (on PSX-place)

Yes, i know maybe its a lot of works... but is the mos easy way to load PS1 games on PS2, just convert it to VCD then launch it, i alredy tried with POPS VCD manager

thanks

**Comment by israpps** [comment]
> Yes, i know maybe its a lot of works... but is the mos easy way to load PS1 games on PS2, just convert it to VCD then launch it

That is EXACTLY what POPSLoader achieves...
https://www.psx-place.com/resources/popsloader.1396/

**Comment by WolfRamiO74** [comment]
> > Yes, i know maybe its a lot of works... but is the mos easy way to load PS1 games on PS2, just convert it to VCD then launch it
> 
> That is EXACTLY what POPSLoader achieves... https://www.psx-place.com/resources/popsloader.1396/

okay

I tried with "POPS VCD MANAGER":

Everything OK until the moment of loading the VCDs from the OPL... some make an error and others simply turn the screen black and then return to the OPL.

with POPSLoader:

if I open it from uLaunchELF ISR, I get "this file isn´t an ELF"


I'M TRYING TO DO ALL THIS USING A MX4SIO AND exFAT.

I think the issue with "POPS VCD MANAGER" is that it has no support for booting VCDs from the MX4SIO.

Thank you!

**Comment by israpps** [comment]
> I think the issue with "POPS VCD MANAGER" is that it has no support for booting VCDs from the MX4SIO.
> 
> Thank you!

POPStarter will never support MX4SIO

**Comment by WolfRamiO74** [comment]
> > I think the issue with "POPS VCD MANAGER" is that it has no support for booting VCDs from the MX4SIO.
> > Thank you!
> 
> POPStarter will never support MX4SIO

can be added support for MX4SIO to BDM Assault?

**Comment by israpps** [comment]
> > > I think the issue with "POPS VCD MANAGER" is that it has no support for booting VCDs from the MX4SIO.
> > > Thank you!
> > 
> > 
> > POPStarter will never support MX4SIO
> 
> can be added support for MX4SIO to BDM Assault?

It can, but it will not work on MX4SIO
