### ISSUE TITLE
Backup PS2 Saves with their original file dates?

### ISSUE THREAD

**Issue by R7CrazyCanucks** [israpps/wLaunchELF_ISR#51]
Does this version of wLaunchELF preserve the original file creation dates of my PS2 save files when backing them up to a USB?

**Comment by israpps** [comment]
> Does this version of wLaunchELF preserve the original file creation dates of my PS2 save files when backing them up to a USB?

as long as you use the PSUPaste option. wich encapsulates your save files on a PSU Container, wich preserves every property from the MC Filesystem for that save file (date Included)
