### ISSUE TITLE
PS2 Controller not working

### ISSUE THREAD

**Issue by rustiferch** [israpps/wLaunchELF_ISR#53]
Hi Team,
I've found that if I use wLaunchELF BOOT, my PS2 controller works flawlessly.
If I try any other build, such as the EXFAT+MX4SIO build (DS34 or the non-DS34) the controller doesn't work at all.
Any idea what may be causing this?
Thanks :)

**Comment by israpps** [comment]
Could you try without MX4SIO?

**Comment by rustiferch** [comment]
Yes, the flat "boot.elf" works fine. Just no mx4sio.

**Comment by rustiferch** [comment]
I did however have a hunt through these issues logs and found a link to this build to fix another issue. It seems to also fix my issue. 

https://github.com/israpps/wLaunchELF_ISR/issues/52#issuecomment-1682636504
