### ISSUE TITLE
[ISSUE]: 128mb chinese card reports 0kb free

### ISSUE THREAD

**Issue by Nemo1985** [israpps/wLaunchELF_ISR#61]
### Checks

- [X] I have checked existing [__Issue reports__](https://github.com/israpps/wLaunchELF_ISR/issues) for duplicates and found none
- [X] I downloaded wLaunchELF from this repository or the [official download link](https://israpps.github.io/20210113_wLaunchELF_isr/)

### Console model

SCPH-77004

### wLaunchELF commit code

41e4ebe

### Describe the issue

I'm testing a couple of 128mb memory cards bought from Aliexpress some years ago. I tested them and they seem to work fine but when I open them with BOOT-EXFAT-NO_NETWORK-MX4SIO.elf it reports 0B free and I being unable to write it, it doesn't even list the files inside. While if I use LaunchELF v4.43a everything works fine (copy from and to).

**Comment by israpps** [comment]
MX4SIO driver hooks into the SIO2[^1] driver to use the MX4SIO card on the slot 1 (`mc0:/`)...

So it shouldn't work.

Anyways, 128mb cards tend to be quite crappy. So I cannot guarantee it to work on all cards

[^1]: SIO2 bus that controls memory card, Dualshock and remote control receptor

**Comment by Nemo1985** [comment]
I'm sure those chinese mc are quite crappy. I downloaded the build without MX4SIO support (which didn't work it showed a empty sd card) and now it detects the memory card fine.

Thank you.
