### ISSUE TITLE
Issue copying files

### ISSUE THREAD

**Issue by TheBloodstomper** [israpps/wLaunchELF_ISR#7]
Hi, 

First of all, thank you very much for reviving this project so many years later. I was really happy to be able to use your tool but... Copying files just doesn't work on my PS2. NTSC Japanese 50K (a ceramic white).

I used the HDD version, the normal, the uncompressed. But none of them worked copying files. The copy crashes with 0kb and it sometimes creates a corrupted file.

I already happened to me with some older versions of ule on this PS2. I can't really remember how many versions didn't worked on my console but I can say that the issue didn't happened with the ule included in the iso FHDB1.93.

Any advice? Thanks in advance.

**Comment by israpps** [comment]
> Hi,
> 
> First of all, thank you very much for reviving this project so many years later. I was really happy to be able to use your tool but... Copying files just doesn't work on my PS2. NTSC Japanese 50K (a ceramic white).
> 
> I used the HDD version, the normal, the uncompressed. But none of them worked copying files. The copy crashes with 0kb and it sometimes creates a corrupted file.
> 
> I already happened to me with some older versions of ule on this PS2. I can't really remember how many versions didn't worked on my console but I can say that the issue didn't happened with the ule included in the iso FHDB1.93.
> 
> Any advice? Thanks in advance.

What where you trying to copy (a file?, a bunch of files?, a folder with a bunch of files?, a bunch of folders with a bunch of files?)

target device?
Source device?
