### ISSUE TITLE
use MXS

### ISSUE THREAD

**Issue by WolfRamiO74** [israpps/wLaunchELF_ISR#77]
It would be very nice if you could have a way to use the MX4SIO and a USB device at the same time.

This way we can leave both things installed at the same time so we don't have to remove one to use the other.

Thank you!

**Comment by israpps** [comment]
what you ask for is already implemented. wLaunchELF maps up to 10 bdm devices at the same time. so you have plenty of space for mx4sio and usb to coexist

**Comment by WolfRamiO74** [comment]
Since which version can I find that feature?

I'm going to update mine since the one I'm using only shows the USB device if both are connected (the MX4SIO and the USB device) at the same time.

Thank from the reply and your efforts to develop <3

**Comment by israpps** [comment]
> Since which version can I find that feature?
> 
> I'm going to update mine since the one I'm using only shows the USB device if both are connected (the MX4SIO and the USB device) at the same time.
> 
> Thank from the reply and your efforts to develop <3

before 4.43x_isr was made

Just enter mass:/ and go back to make wLaunchELF refresh the list of mass:/ devices

**Comment by WolfRamiO74** [comment]
OMG!!! I feel so distracted right now, sorry, I posted on the wrong app!

I thought I had published on the OPL GitHub...

Again, sorry for that.

**Comment by israpps** [comment]
> OMG!!! I feel so distracted right now, sorry, I posted on the wrong app!
> 
> I thought I had published on the OPL GitHub...
> 
> Again, sorry for that.

np
