### ISSUE TITLE
[ISSUE]: I can no longer access MC from slot 2

### ISSUE THREAD

**Issue by Jaajees** [israpps/wLaunchELF_ISR#84]
### Checks

- [X] I have checked existing [__Issue reports__](https://github.com/israpps/wLaunchELF_ISR/issues) for duplicates and found none
- [X] I downloaded wLaunchELF from this repository or the [official download link](https://israpps.github.io/20210113_wLaunchELF_isr/)

### Console model

SCPH-90010

### wLaunchELF commit code

Comit: 945d787

### Describe the issue

MC in slot 2 is not recognized by wLaunchElf

**Comment by israpps** [comment]
you downloaded a build with MX4SIO support enabled?

**Comment by Jaajees** [comment]
> você baixou uma compilação com suporte MX4SIO habilitado?

I want to get MX4SIO

So it is recommended to have two versions, one with MX4SIO support and one without support?

**Comment by israpps** [comment]
MX4SIO support hooks into SIO2MAN module to make sure only its own data payloads reach slot 2.

That's why mc1: is inaccessible
